const courses=[['Ruso desde cero','A0','Saludos, alfabeto y frases esenciales'],['Ruso A1','A1','Vida diaria y conversaciones cortas'],['Ruso A2','A2','Viajes, compras y situaciones reales'],['Ruso B1','B1','Conversación con más confianza'],['Ruso B2','B2','Fluidez, cultura y argumentación'],['Ruso C1','C1','Ruso avanzado y matices'],['Ruso para viajar','TEMÁTICO','Sobrevive y disfruta tu viaje'],['Ruso para ligar','TEMÁTICO','Conecta y conversa naturalmente']];
const saved=JSON.parse(localStorage.getItem('mova-state')||'{"progress":0,"streak":0}');
const views=[...document.querySelectorAll('.view')],nav=[...document.querySelectorAll('.nav-link')];
function show(view){views.forEach(v=>v.classList.toggle('active',v.id===view+'-view'));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===view));document.getElementById('crumb').textContent=view.toUpperCase();document.getElementById('page-title').textContent={home:'Hola, María',courses:'Mis cursos',games:'Juegos MOVA',chat:'Chat con Nika',teacher:'Cabinet pedagógico',admin:'Administración',builder:'MOVA para profesores'}[view];}
nav.forEach(n=>n.onclick=()=>show(n.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.getElementById('mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.getElementById('course-grid').innerHTML=courses.map((c,i)=>`<article class="course-card"><p>${c[1]}</p><h3>${c[0]}</h3><span>${c[2]}</span><button data-course="${i}">Abrir curso →</button></article>`).join('');document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{saved.progress=Math.max(saved.progress,10);save();show('courses');alert('Curso disponible en MOVA. Los siguientes módulos se abrirán aquí.');});
function save(){localStorage.setItem('mova-state',JSON.stringify(saved));document.getElementById('stat-progress').textContent=saved.progress+'%';document.getElementById('home-progress').style.width=saved.progress+'%';document.getElementById('stat-streak').textContent=saved.streak||0;}save();
let card=0,flipped=false;const cards=[['Спасибо','Gracias'],['Привет','Hola'],['Пожалуйста','Por favor'],['До свидания','Adiós']];function drawCard(){document.getElementById('card-russian').textContent=flipped?cards[card][1]:cards[card][0];document.getElementById('card-spanish').textContent=flipped?'Toca para volver al ruso.':'Toca la tarjeta para ver la traducción.';document.getElementById('flash-count').textContent=(card+1)+' / '+cards.length;}document.getElementById('flash-card').onclick=()=>{flipped=!flipped;drawCard()};document.getElementById('flash-next').onclick=()=>{card=(card+1)%cards.length;flipped=false;drawCard()};document.getElementById('flash-prev').onclick=()=>{card=(card+cards.length-1)%cards.length;flipped=false;drawCard()};drawCard();
let x=8,y=8;const player=document.getElementById('player');function move(dir){if(dir==='up')y=Math.max(8,y-42);if(dir==='down')y=Math.min(176,y+42);if(dir==='left')x=Math.max(8,x-42);if(dir==='right')x=Math.min(176,x+42);player.style.left=x+'px';player.style.top=y+'px';if(x>=176&&y>=176){document.getElementById('maze-message').textContent='¡Llegaste! Кофе, пожалуйста.';saved.progress=Math.min(100,saved.progress+10);saved.streak=(saved.streak||0)+1;save();}}document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.move));document.addEventListener('keydown',e=>{const direction={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key];if(direction)move(direction)});
function nika(text){const t=text.toLowerCase();if(/curso|empezar|nivel/.test(t))return 'Te recomiendo comenzar con Ruso desde cero A0 o hacer el test de nivel.';if(/pronun|audio|voz/.test(t))return 'En cada lección podrás escuchar la palabra, grabar tu voz y compararla con la pronunciación de Nika.';if(/progreso/.test(t))return 'Tu progreso se guarda en tu navegador en esta demo. En la versión real se guardará en tu cuenta.';return 'Estoy en modo demo. Puedo ayudarte con cursos, pronunciación y progreso.';}function send(text){if(!text.trim())return;const m=document.getElementById('messages');m.insertAdjacentHTML('beforeend',`<div class="message user">${text.replace(/[<>]/g,'')}</div><div class="message nika">${nika(text)}</div>`);m.scrollTop=m.scrollHeight;}document.getElementById('chat-form').onsubmit=e=>{e.preventDefault();const i=document.getElementById('chat-input');send(i.value);i.value=''};document.querySelectorAll('.prompt').forEach(b=>b.onclick=()=>send(b.textContent));
document.getElementById('teacher-file').onchange=e=>document.getElementById('upload-status').textContent=e.target.files[0]?`Preparado: ${e.target.files[0].name}. En producción se guardará en la biblioteca de MOVA.`:'Los archivos se almacenarán en la nube al conectar la versión de producción.';document.getElementById('new-lesson').onclick=()=>alert('Nueva lección: aquí se abrirá el editor de texto, video, imágenes, GIF, presentación y ejercicios.');
